### ISSUE TITLE
这套编译脚本

### ISSUE THREAD

**Issue by MaurUppi** [kenzok8/openwrt_Build#13]
1. 有没有本地编译脚本呢？
2. 可否加入[mlnx网卡驱动](https://github.com/allegro0132/Openwrt-mlnx-ofed) 到x86的自动编译固件中？ 我修改过的MakeFile，不需要在编译过程交互输入了。 
[Makefil.txt](https://github.com/kenzok8/openwrt_Build/files/7740548/Makefil.txt)

**Comment by qingkooo** [comment]
12.15-openwrt-rockchip-armv8-nanopi-r2s-squashfs-sysupgrade
更改了lan口的ip后怎么都无法访问了，提示无效的ip或证书
只能退回到10.29继续用
