### ISSUE TITLE
about the compile firmware

### ISSUE THREAD

**Issue by qyingkou** [kenzok8/openwrt_Build#17]
*Question-one: 
I can't find download entry in your github-actions, how can I download the fireware directly from it?

*Question-two:
Thank you for providing website as https://op.dllkids.xyz to download.
What is the difference between “firmware” and “op / firmware” folder？

Thanks again for your works and convenience！

**Comment by kenzok8** [comment]
1、https://github.com/kenzok8/openwrt_Build/releases or https://op.dllkids.xyz/op/
2、firmware is the latest 21.02 compilation of the openwrt official website source code
3、 under op/firmware corresponds to the firmware compiled by the github-actions
