### ISSUE TITLE
编译错误，请老大查看一下

### ISSUE THREAD

**Issue by jiawm** [kenzok8/openwrt_Build#20]
Applying ./patches/000-quic-go-1.18-fix.patch using plaintext: 
patching file go.mod
Hunk #1 FAILED at 16.
1 out of 1 hunk FAILED -- saving rejects to file go.mod.rej
patching file go.sum
Hunk #1 FAILED at 139.
Hunk #2 FAILED at 147.
2 out of 2 hunks FAILED -- saving rejects to file go.sum.rej
Patch failed!  Please fix ./patches/000-quic-go-1.18-fix.patch!
make[3]: *** [Makefile:95: /workdir/openwrt/build_dir/target-x86_64_musl/adguardhome-0.108.0-b.6/.prepared_4280608ceea4899dbd48df981b487537_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/workdir/openwrt/package/kenzo/adguardhome'
time: package/kenzo/adguardhome/compile#0.29#0.13#0.36
    ERROR: package/kenzo/adguardhome failed to build.
make[2]: *** [package/Makefile:116: package/kenzo/adguardhome/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by kenzok8** [comment]
go.mod.rej 补丁错误，你是本地编译码？
如果是本地，运行下
rm -rf ./feeds && ./scripts/feeds update -a && ./scripts/feeds install -a && rm -rf ./tmp && make menuconfig
重新跑一次
