### ISSUE TITLE
请问如何设置动态链路聚合

### ISSUE THREAD

**Issue by qyingkou** [kenzok8/openwrt_Build#21]
忐忑请教ken大Openwrt的链路聚合问题，如下：

问题背景：
我的交换机（Tplink sg-3218）支持动态链路聚合功能
我的软路由（NanoPi R4S，安装Openwrt v01.18 / kenzo (Mar)固件）作为旁路由使用（仅用了一个lan口）

我的问题：
我想把R4S的两个网口都用起来，即通过动态链路聚合协议实现双网口叠加速度。但当前对Openwrt设置不熟悉，摸索了一阵子还是没有思路。
我想请教：
- 该版本固件（Openwrt v01.18 / kenzo (Mar)）支持链路聚合设置吗？
- 如果支持，那么该如何进行双lan口聚合设置呢？

感谢老大指明方向，感激。

**Comment by qyingkou** [comment]
今天又在该系统下找了一遍还是没找到网口聚合选项，期待ken大抽空给结论。🙏

**Comment by kenzok8** [comment]
我不知道你的需求是wan口的汇聚还是lan口汇聚
另外建议你网上找找教程吧，
https://post.smzdm.com/p/av7o06mn/

**Comment by qyingkou** [comment]
谢谢提供的教程，受用。
我希望将这两个口同时作为lan口来使用（即双lan口聚合，连接2条线到交换机），实现2Gbps的带宽。

您的资源站中有文章中所说的这三个协议插件吗：
- kmod-bonding
- proto-bonding
- luci-proto-bonding

系统软件包中可以找到他们但无法安装成功，继续求助

**Comment by masx200** [comment]
> 谢谢提供的教程，受用。 我希望将这两个口同时作为lan口来使用（即双lan口聚合，连接2条线到交换机），实现2Gbps的带宽。
> 
> 您的资源站中有文章中所说的这三个协议插件吗：
> 
> * kmod-bonding
> * proto-bonding
> * luci-proto-bonding
> 
> 系统软件包中可以找到他们但无法安装成功，继续求助

听说内核模块要重新编译进去才行

**Comment by masx200** [comment]
https://www.right.com.cn/forum/thread-534350-1-1.html

--force-depends
