### ISSUE TITLE
固件中的 IPSec VPN Server 不见了

### ISSUE THREAD

**Issue by qingkooo** [kenzok8/openwrt_Build#23]
问题背景：
在之前的固件（几个大版本前）中内置了IPSec VPN Server这个插件，非常简单容易上手。
而当前编译固件（Openwrt v03.31 / kenzo (Mar)）中，界面上是找不到了，已安装中也找不到踪迹。

我的问题：
我该如何找到IPSec VPN Server这款插件，以及安装到此固件中去呢？
我的设备是 友善NanoPI R4S，请您抽空指教下。

感谢🙏

**Comment by kenzok8** [comment]
https://op.dllkids.xyz/packages/aarch64_cortex-a72/?filter=IPSec

**Comment by qingkooo** [comment]
感谢您的回复。
我还不清楚这些词的含义：
- cortex-a72
- generic
麻烦告知哈

**Comment by kenzok8** [comment]
cortex-a72 架构 然后搜索框里查询ipsec

**Comment by qingkooo** [comment]
贵站的IPSec_vpn_server插件我可以成功安装到R2S但无法安装到R4S（提示未知的package无法安装）。
而R2S的openwrt网络接口列表中，发现IPSEC_SERVER列表项提示“不支持的协议类型”，没有配套的协议插件。
如下图：
<img width="940" alt="image" src="https://user-images.githubusercontent.com/25194108/166168001-ac41e09b-f32c-4d08-ad84-0cae1d8e9945.png">

而点击上图链接“安装扩展协议”，也找不到IPSec相关协议项。


## 我的问题：
- IPSec_vpn_server插件对应的协议应该安装哪个呢，您的资源站上有吗？
- IPSec_vpn_server插件将来可以支持R4S吗

看到请烦劳回复，万分感谢您
