### ISSUE TITLE
2月5日的R4S固件依旧不能登陆

### ISSUE THREAD

**Issue by rainoooooo** [kenzok8/openwrt_Build#27]
这几天改过的都连续测试了，依然无法登陆， 我暂时换了别的在用，

**Comment by kenzok8** [comment]
按理说不会啊，IP有没有对？默认IP是192.168.1.252，然后wan口lan口区分下

**Comment by rainoooooo** [comment]
IP是192.168.1.152，IP是192.168.1.3也试了，还写了几次卡试几次都不行

发自我的 iPhone

在 2023年2月7日，22:25，有種 ***@***.***> 写道：

﻿

按理说不会啊，IP有没有对？默认IP是192.168.1.252，然后wan口lan口区分下

**Comment by rainoooooo** [comment]
打错字，192.168.1.252

发自我的 iPhone

在 2023年2月7日，22:25，有種 ***@***.***> 写道：

﻿

按理说不会啊，IP有没有对？默认IP是192.168.1.252，然后wan口lan口区分下

**Comment by rainoooooo** [comment]
ip还是在github复制的呢，没错的

发自我的 iPhone

在 2023年2月7日，22:25，有種 ***@***.***> 写道：

﻿

按理说不会啊，IP有没有对？默认IP是192.168.1.252，然后wan口lan口区分下

**Comment by yyetss** [comment]
2/16版本r4s 192.168.1.252依旧无法登录。lan wan互换也不行
