### ISSUE TITLE
大佬fork之后编译出来的Lienol服务变成了网络存储

### ISSUE THREAD

**Issue by m0eak** [kenzok8/openwrt_Build#29]
![image](https://github.com/kenzok8/openwrt_Build/assets/50049180/4ed52abf-9873-4769-820d-e59d0a996587)
如图所示，这个是为什么啊

**Comment by m0eak** [comment]
![image](https://github.com/kenzok8/openwrt_Build/assets/50049180/41d4d1de-ab64-48f0-9fe5-fbcaba071ee8)

**Comment by m0eak** [comment]
下载你的release里的也是这样..

**Comment by kenzok8** [comment]
https://github.com/kenzok8/small-package/commit/cb903c5813e7785107d88bfdc5c4e45d151783c3
因为改变了插件显示的目录；lean源码下没问题，估计是bug，重新恢复了

**Comment by m0eak** [comment]
> [kenzok8/small-package@cb903c5](https://github.com/kenzok8/small-package/commit/cb903c5813e7785107d88bfdc5c4e45d151783c3) 因为改变了插件显示的目录；lean源码下没问题，估计是bug，重新恢复了

ok了
