### ISSUE TITLE
最新编译的lean包装完主题报错

### ISSUE THREAD

**Issue by rayle2** [kenzok8/openwrt_Build#47]
要ssh到后台切换成bootstrap才行
![QQ截图20241129180222](https://github.com/user-attachments/assets/134db118-e7be-4ddd-b9b2-4afa62928eec)

**Comment by kenzok8** [comment]
luci-theme-design 主题出错了，是因为默认开启了与argon冲突了，已经取消

**Comment by rayle2** [comment]
> luci-theme-design 主题出错了，是因为默认开启了与argon冲突了，已经取消

啥时候有新包大大，11.30那个还是报这个错

**Comment by rayle2** [comment]
> luci-theme-design 主题出错了，是因为默认开启了与argon冲突了，已经取消

12.08的包还是在报错

**Comment by kenzok8** [comment]
先等等，我在测试，因为L大用了luci-23.05了，所以老早的luci 18.06就不适合了

**Comment by rayle2** [comment]
> 先等等，我在测试，因为L大用了luci-23.05了，所以老早的luci 18.06就不适合了

感谢回复
