### ISSUE TITLE
Some Feedback after use Openwrt_Build

### ISSUE THREAD

**Issue by fengFork** [kenzok8/openwrt_Build#5]
非常感谢kenzo大神写的build脚本。非常好用

试用下来有几个建议：
1.  build 脚本中大量使用了${{ env.date3 }}, ${{ env.date2 }}等变量作为tag name, file name。感觉env.date4最好用，只有月，日，没有年信息将来搞不清这个build是哪一年出的。
2. Leon脚本的162行多了一个空格
  ${{ env.date3 }} _Lean
  应该去掉空格改成${{ env.date3 }}_Lean
3. 建议把日期和Lean翻过来改成Lean_${{ env.date3 }} 或 Lean_${{ env.date4 }}，看起来更自然。其它各处也都是把Lean放在日期前面比放在后面更舒服。
4. ${{matrix.target}}这个变量好像一直没有值？
以上4点对Lienol.yml也适用

5. Lienol的第81行 sed -i '5s/#//' feeds.conf.default 这句需要删掉了
6. Lienol的第102行AdGuardHome应该改为adguardhome
7. litte/commit/Lienoldiffconfig里最好加一句
`# CONFIG_PACKAGE_kmod-crypto-misc is not set`
不加这句Lienol的main branch编译不过，加上这句后main branch也可以编译过了。

谢谢。

**Comment by kenzok8** [comment]
对于提的意见与建议，虚心接受！
