### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by fengFork** [kenzok8/openwrt_Build#6]
merge了lean.yml和lienol.yml的最新改动后，编译错误
make defconfig时出现以下错误
```
tmp/.config-package.in:65544: syntax error
tmp/.config-package.in:65543: invalid statement
tmp/.config-package.in:65544: invalid statement
tmp/.config-package.in:65545: invalid statement
tmp/.config-package.in:65546: invalid statement
make: *** [/home/runner/work/openwrt_Build/openwrt_Build/openwrt/include/toplevel.mk:120: defconfig] Error 1
```
经检查是helloworld的以下改动导致语法错误(我也看不出什么错误，反正编译器报的错误在这里)
https://github.com/fw876/helloworld/commit/c4a07886a6fd20a77087821049d5e6975b47ca03

两个问题请教一下
1. 以上commit已经merge到kenzok8/litte了，不知道你是否跑出来同样错误，可能需要回退。
2. 既然kenzok8/litte里面已经有luci-app-ssr-plus了，不清楚lean.xml lienol.xml为什么还需要
···
        echo "src-git ssrp https://github.com/fw876/helloworld.git" >> ./feeds.conf.default
···
有了这句话，litte里面的luci-app-ssr-plus等于没有用。

**Comment by fengFork** [comment]
helloworld上有bug fix了。
https://github.com/fw876/helloworld/commit/9d1d1b3930ad89166cc37f18aac840404d3b6bc3

还是想了解一下，既然kenzok8/litte里面已经有luci-app-ssr-plus了，代码基本同步。为什么还要helloworld也加入feeds？

**Comment by kenzok8** [comment]
因为helloworld里的包与passall重叠，谁更新到最新也不一致，所以保险期间是把hellworld放入了feeds里
