### ISSUE TITLE
How to output openwrt-x86-64-generic-ext4-combined.img.gz file?

### ISSUE THREAD

**Issue by drejohnson** [kenzok8/openwrt_Build#9]

**Comment by kenzok8** [comment]
![Uploading photo_2021-11-12_14-49-59.jpg…](
![photo_2021-11-12_14-50-04](https://user-images.githubusercontent.com/39034242/141423066-c1f3677b-5b89-4f89-82cb-05249992b2cb.jpg)
)

**Comment by kenzok8** [comment]
![photo_2021-11-12_14-49-59](https://user-images.githubusercontent.com/39034242/141423117-d686a572-99a0-446d-b108-bd87d47335a2.jpg
![photo_2021-11-12_14-50-04](https://user-images.githubusercontent.com/39034242/141423128-703fbe44-9141-42f6-ac3f-93f5a4298623.jpg)
)

**Comment by kenzok8** [comment]
![photo_2021-11-12_14-49-59](https://user-images.githubusercontent.com/39034242/141423167-2fd04799-10d7-4b30-acdf-af8168030f78.jpg)

**Comment by kenzok8** [comment]
![photo_2021-11-12_14-50-04](https://user-images.githubusercontent.com/39034242/141423187-08d79fc8-1984-4419-b498-473d38885630.jpg)
